### ISSUE TITLE
nonlocal mqtt

### ISSUE THREAD

**Issue by luxus** [cblomart/zwaymqtt#2]
it's possible to use  https://www.cloudmqtt.com/ for mqtt?
i need to enter username and password somewhere :D

**Comment by cblomart** [comment]
I did see you request. Currenty it doesn't support connecting to mqtt via username/password.

**Comment by luxus** [comment]
oh shit.. i can't make a pull request because i don't speak any golang :/
i use z-way on a raspberry pi 1 b+ and don't want to run the mqtt server on that machine, i want to use the mqtt bridge to connect z-way to home-assistant

**Comment by cblomart** [comment]
@luxus, Could you test the release i just made? (simple changes but didn't test much).

**Comment by luxus** [comment]
yes i will do it now.. takes a moment

**Comment by luxus** [comment]
```
May 07 22:30:56 kaipi zwaymqtt[3922]: 2016/05/07 22:30:56 Z-Way refresh rate: 3
May 07 22:30:56 kaipi zwaymqtt[3922]: 2016/05/07 22:30:56 MQTT server: m21.cloudmqtt.com:16704
May 07 22:30:56 kaipi zwaymqtt[3922]: panic: Not Authorized
May 07 22:30:56 kaipi zwaymqtt[3922]: goroutine 1 [running]:
May 07 22:30:56 kaipi zwaymqtt[3922]: panic(0x3331f0, 0x1071e490)
May 07 22:30:56 kaipi zwaymqtt[3922]: C:/Go/src/runtime/panic.go:464 +0x330
May 07 22:30:56 kaipi zwaymqtt[3922]: main.main()
May 07 22:30:56 kaipi zwaymqtt[3922]: C:/Users/cblomart.FINBEL/Documents/go/src/github.com/cblomart/zwaymqtt/zwaymqtt.go:822 +0x7a8
```

**Comment by luxus** [comment]
@cblomart i think you forgot to update the https://github.com/cblomart/zwaymqtt/blob/master/etc/systemd/system/zwaymqtt.service .. 
and  the config as well 

i got it running :D 

i will test it tomorrow

**Comment by cblomart** [comment]
Good to know.

If possible i wouldn't change the service as it doesn't require the extra parameters for mqtt authentication.
Althought i concede that configuring it would require modifiying the service file...
