### ISSUE TITLE
adding the retain flag to the messages

### ISSUE THREAD

**Issue by luxus** [cblomart/zwaymqtt#5]
please add the retain flag to the messages so the messages stay on the server until an update.
its important for other apps to readout the state of an sensor and not just the updates

**Comment by cblomart** [comment]
retain flag set to true. I added also mqtt webservice and tls protocol altought untested.

**Comment by luxus** [comment]
mhh they are not retained on my server.. @cblomart 
i send a message by hand and it was there forever.. so it don't look like a server issue..
