### ISSUE TITLE
update all messages on launch

### ISSUE THREAD

**Issue by luxus** [cblomart/zwaymqtt#6]
not the most important think but it would be great if the topic got filled with the states of the z-way devices on launch and don't wait for update.. its easier for a fresh start to see all the available messages and better on some values that unusually got changed

**Comment by cblomart** [comment]
Do you have issues there?

zwaymqtt first read an initial update from zway (with timestamp 0 'epoch'). This will contain the status of all devices.
The update will be parsed to mqtt topics.
The same update will be parsed to push states to topics.

Theoricaly, all updates should get trought to mqtt at launch... if this doesn't happen it needs to be checked.

**Comment by luxus** [comment]
I will check that with the new version.
Blomart Cédric notifications@github.com schrieb am Mo., 9. Mai 2016 um
17:16:

**Comment by cblomart** [comment]
Can you test from docker hub: cbomart/rpi-zwaymqtt:master

Please use environment variables to configure:
- MQTT topic root = ZWAY_HOME
- MQTT server = MQTT_SERVER
- MQTT password = MQTT_PASSWORD
- MQTT username = MQTT_USERNAME
- MQTT protocol = MQTT_PROTOCOL
- Z-Way server name = ZWAY_SERVER
- Z-Way username = ZWAY_USERNAME
- Z-Way password = ZWAY_PASSWORD
- Z-Way refresh rate = ZWAY_REFRESH

not that you need to fill them all, there are some default

**Comment by luxus** [comment]
now nothing happens.. 

```
$ ./zwaymqtt
2016/05/09 22:00:28 Setting port 8083 on given Z-Way server
2016/05/09 22:00:28 Starting Z-Way to mqtt gateway...
2016/05/09 22:00:28 Z-Way server: zway:8083
2016/05/09 22:00:28 Z-Way user: admin
2016/05/09 22:00:28 Z-Way refresh rate: 30
2016/05/09 22:00:28 MQTT server: m21.cloudmqtt.com:16704
```

with all the variables could you make it possible to load a config file?
something like -c path/zwaymqtt.conf
at best with a default behavior to search for a config in ~/.zwaymqtt/config.conf or something like that

**_update:**_ ahh updates/messages are coming in.. but no messages on start

**Comment by luxus** [comment]
i got the config part done with the --env-file from docker.
i updated my dockerfile to just 5 lines! https://github.com/luxus/rpi-docker-zwaymqtt

**Comment by luxus** [comment]
i installed a local mqtt and i see the messages.. looks like cloudmqtt don't like your retained flag.
i even see the messages of the setpoint
